image: node:12.14.0

pipelines:
  default:
    - step:
        name: Build, migrations and tests
        deployment: test
        caches:
          - node
        script:
          - npm ci
          - npm run build
        services:
          - postgres
          - redis
  branches:
    staging:
      - step:
          name: Staging tests
          caches:
            - node
          script:
            - npm ci
      - step:
          name: Staging DEPLOY
          caches:
            - node
          deployment: staging
          script:
            - npm run build
            - cd heroku
            - rm -rf bin dist public .git mails ormconfig.js package.json package-lock.json
            - cp -r ../bin ../dist ../public ../mails ../ormconfig.js ../package.json ../package-lock.json ./
            - sed "s/rm -rf dist && nest build/echo NO NEED BUILD PREFERATION/" -i package.json
            - git init
            - git config user.email "razvanlomov@gmail.com"
            - git config user.name "Razzwan-CI"
            - git add .
            - git commit -m 'dynamic version'
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$STAGING_APP_NAME.git -f HEAD:master
    master:
      - step:
          name: Production tests
          caches:
            - node
          script:
            - npm ci
      - step:
          name: Production DEPLOY
          deployment: production
          caches:
            - node
          script:
            - npm run build
            - cd heroku
            - rm -rf bin dist public .git mails ormconfig.js package.json package-lock.json
            - cp -r ../bin ../dist ../public ../mails ../ormconfig.js ../package.json ../package-lock.json ./
            - sed "s/rm -rf dist && nest build/echo NO NEED BUILD PREFERATION/" -i package.json
            - sed "s/staging-altiore-api/altiore-api/" -i app.json
            - git init
            - git config user.email "razvanlomov@gmail.com"
            - git config user.name "Razzwan-CI"
            - git add .
            - git commit -m 'dynamic version'
            - git status
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$PRODUCTION_APP_NAME.git -f HEAD:master

definitions:
  services:
    postgres:
      image: postgres:11.6
      restart: always
      volumes:
        - ./docker/postgres:/docker-entrypoint-initdb.d
      environment:
        POSTGRES_DB: 'pipelines'
        POSTGRES_USER: 'test_user'
        POSTGRES_PASSWORD: 'test_user_password'
    redis:
      image: redis
