import { COLUMN_TYPE, IMove, MOVE_TYPE } from '../move';
import { STATUS_NAME } from '../status';

export const architect_feat: Array<IMove> = [
  {
    column: [COLUMN_TYPE.TO_DO, 1],
    from: STATUS_NAME.CREATING,
    to: [{ type: MOVE_TYPE.PUSH_FORWARD, status: STATUS_NAME.ESTIMATION_BEFORE_ASSIGNING }],
  },
  {
    column: [COLUMN_TYPE.IN_PROGRESS, 2],
    from: [STATUS_NAME.ASSIGNING_RESPONSIBLE, STATUS_NAME.ESTIMATION_BEFORE_ASSIGNING],
    to: [{ type: MOVE_TYPE.PUSH_FORWARD, status: STATUS_NAME.ESTIMATION_BEFORE_TO_DO }],
  },
  {
    column: [COLUMN_TYPE.DEVELOPMENT, 3],
    from: [
      STATUS_NAME.ESTIMATION_BEFORE_PERFORMER,
      STATUS_NAME.ASSIGNING_PERFORMER,
      STATUS_NAME.ESTIMATION_BEFORE_TO_DO,
      STATUS_NAME.READY_TO_DO,
      STATUS_NAME.IN_PROGRESS,
      STATUS_NAME.AUTO_TESTING,
      STATUS_NAME.PROF_REVIEW,
    ],
  },
  {
    column: [COLUMN_TYPE.TESTING, 4],
    from: [STATUS_NAME.ESTIMATION_BEFORE_TEST, STATUS_NAME.READY_TO_TEST, STATUS_NAME.TESTING],
  },
  {
    column: [COLUMN_TYPE.REVIEW, 5],
    from: STATUS_NAME.ARCHITECT_REVIEW,
    to: [
      { type: MOVE_TYPE.PUSH_FORWARD, status: STATUS_NAME.READY_TO_DEPLOY },
      { type: MOVE_TYPE.BRING_BACK, status: STATUS_NAME.READY_TO_TEST },
      { type: MOVE_TYPE.BRING_BACK, status: STATUS_NAME.READY_TO_DO },
    ],
  },
  {
    column: [COLUMN_TYPE.ESTIMATION, 6],
    from: STATUS_NAME.DEPLOYED_ARCHITECT_ESTIMATION,
    to: [{ type: MOVE_TYPE.PUSH_FORWARD, status: STATUS_NAME.DEPLOYED_COMMUNITY_ESTIMATION }],
  },
  {
    column: [COLUMN_TYPE.DONE, 7],
    from: STATUS_NAME.DONE,
  },
];
